### ISSUE TITLE
Duplicidade de RA

### ISSUE THREAD

**Issue by fabiosampaio12** [6975usa/portal#12]
O delegado da 2ª Del SM entrou em contato informando que na JSM-020 -  Estância foram realizados alistamentos tanto Online (realizados pelos cidadãos) quanto os realizados pela Secretária para os que não possuem CPF e nem Email. Diante disso, foi verificado que ao realizar o alistamento Online, e após realizar outro pelo Portal (Secretário de JSM) aparece o mesmo RA para cidadãos diferentes. Ao realizar a pesquisa no SERMIL pelo RA só existe o cidadão que se alistou Online.
Exemplo anexo: MAURILHO JOSE DE MELO FRANCA e GABRIEL RIBEIRO DOS SANTOS não foi salvo no sistema.
![duplicidade](https://cloud.githubusercontent.com/assets/12251958/7496088/8abb0128-f3e8-11e4-9fef-5dcdd78b71aa.jpg)

**Comment by wagnerlopes** [comment]
Foi levantado que o Secretário da JSM estava trabalhando incorretamente ao fazer o Alistamento pelo Portal do SERMIL, lançando um RA manualmente, ao invés de deixar o próprio sistema criar o RA do cidadão. 
O Alistamento ONLINE, realizado pelo próprio cidadão, está correto e foi efetivado.
O alistamento do Secretário foi incorreto e não foi válido, sendo que o cidadão deverá ser alistado novamente pois não consta do sistema.
Estou verificando se o alistamento manual pelo Portal está deixando imprimir um CAM mesmo quando ocorre erro e o alistamento não funciona, o que pode ser o caso.
