### ISSUE TITLE
CDI so pode ser impresso quando cidadao em "Excesso de Contigente" - Incluir Regra

### ISSUE THREAD

**Issue by 6975usa** [6975usa/portal#2]
A seguinte regra de negocio precisa ser inserida:

CDI so pode ser impresso quando cidadao em "Excesso de Contigente"

**Comment by 6975usa** [comment]
Posso incluir esta regra, Cel, caso o sr queira distribui-la pra mim.

**Comment by wagnerlopes** [comment]
Distribuí usando "Assignee" para seu usuário.

**Comment by 6975usa** [comment]
Alteracao implementada.

**Comment by 6975usa** [comment]
Essa alteracao implicou em mudanca no Sermil-core tambem.
