### ISSUE TITLE
Relatorio 8113 mostra dados divergentes aparentemente.

### ISSUE THREAD

**Issue by 6975usa** [6975usa/portal#7]
Recebi a visita de um militar da Cia C2 da 11RM dizendo que deu destino no Sermil a todos os cidadaos que foram distribuidos a ele. Apesar disso o relatorio 8113 mostrava que ele ainda nao havia distribuido os cidadaos. 
Apesar de eu nao entender muito bem dessa parte do sistema, fiz uma busca e conclui que o militar estava certo. O relatorio deveria mostrar que ele incorporou 22 e dispensou 32 dos 54 cidadaos que foram distribuidos a Cia C2. Mas o relatorio mostra que os 54 estao sem destino.

**Comment by wagnerlopes** [comment]
Isso ocorre porque o Job no banco de dados Oracle está agendo para rodar somente aos sábados e atualizar as informações que são geradas no Rel 8113. 
Foi feito assim porque o processo demorava muito para rodar no banco de dados antigo, agora no EXADATA o processo deve rodar bem mais rápido.
Talvez fosse o caso de passar a rodar o JOB todo dia a noite. Podemos ver isso semana que vem.

**Comment by wagnerlopes** [comment]
Alterei o Job no RDBMS Oracle para rodar todos os dias a partir das 21h, desta forma o Relatório irá apresentar os dados atualizados no dia seguinte para o usuário.
O problema está aparentemente resolvido, ou pelo menos, atenuado.
